#!/bin/bash

FILES=(
  .bash_profile
  .bashrc
  .curlrc
  .gitconfig
  .gitignore
  .npmrc
  .tmux.conf
  .vimrc
)

for f in ${FILES[@]}; do
  ([[ -f ~/$f ]] || [[ -d ~/$f ]]) && rm -rfi ~/$f
  ln -s $PWD/$f ~/$f
done
